import Head from 'next/head';
import { useEffect } from 'react';

import Header from 'components/layout/header';
import Headding from 'components/layout/headding';
import Chevron from 'components/chevron';
import useMouse from 'hooks/useMouse';

export default function Home({ data = {} }) {

  const { eventMousePosition } = useMouse();

  useEffect(() => {
    eventMousePosition('start')
    return () => {
      eventMousePosition('end')
    }
  }, [eventMousePosition])

  return (
    <>
      <Head>
        <title>harleysg portfolio</title>
        <meta name='description' content='Generated by harleysg portfolio' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header menu={data?.menu} />

      <main className={'o-main'}>
        <section className={'o-section'}>
          <div className={'o-wrapper'}>
            <Headding text={data?.sections?.one} />
          </div>
          <Chevron />
        </section>
        <section className={'o-section'} data-theme='gold'>
          <div className={'o-wrapper'}>
            <Headding text={data?.sections?.one} />
          </div>
        </section>
        <section className={'o-section'} data-theme='gray'>
          <div className={'o-wrapper'}>
            <Headding text={data?.sections?.one} />
          </div>
        </section>
        <section className={'o-section'} data-theme='dark'>
          <div className={'o-wrapper'}>
            <Headding text={data?.sections?.one} />
          </div>
        </section>
      </main>

      <div className={'mouse-tracker'}></div>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/hello`);
  const data = await res.json();

  return { props: { data } };
}
