import Head from 'next/head';

import Header from 'components/layout/header';

export default function Home() {
  return (
    <>
      <Head>
        <title>harleysg portfolio</title>
        <meta name='description' content='Generated by harleysg portfolio' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className={'o-main'}>
        <section className={'o-section'}>lorem</section>
      </main>
      <div className={'mouse-tracker'}></div>
    </>
  );
}
